--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-12岿-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_PJ_BRANCH
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_PJ_BRANCH"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PJ_MOVIE
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_PJ_MOVIE"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PJ_REVIEW
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_PJ_REVIEW"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 53 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PJ_SCHEDULE
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_PJ_SCHEDULE"  MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 START WITH 112 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PJ_TICKET
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_PJ_TICKET"  MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PJ_TICKET
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_TICKET" 
   (	"TK_ID" NUMBER, 
	"MMB_ID" VARCHAR2(100 BYTE), 
	"SCD_ID" NUMBER, 
	"MV_ID" NUMBER, 
	"TK_PEOPLE_LIST" VARCHAR2(100 BYTE), 
	"TK_SEAT_LIST" VARCHAR2(2000 BYTE), 
	"TK_PRICE_TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_SCHEDULE" 
   (	"SCD_ID" NUMBER, 
	"BRC_ID" NUMBER, 
	"MV_ID" NUMBER, 
	"SCD_DATE" VARCHAR2(100 BYTE), 
	"SCD_TIME" NUMBER, 
	"SCD_THEATER" NUMBER, 
	"SCD_SEAT_TOTAL" NUMBER, 
	"SCD_SEAT_BOOKED_CNT" NUMBER DEFAULT 0, 
	"SCD_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_REVIEW
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_REVIEW" 
   (	"RV_ID" NUMBER, 
	"MV_ID" NUMBER, 
	"MMB_ID" VARCHAR2(100 BYTE), 
	"RV_CONTENT" VARCHAR2(3000 BYTE), 
	"RV_RATING" NUMBER, 
	"RV_DATE_CREATED" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_MOVIE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_MOVIE" 
   (	"MV_ID" NUMBER, 
	"MV_TITLE" VARCHAR2(100 BYTE), 
	"MV_IMAGE" VARCHAR2(500 BYTE), 
	"MV_DATE_STARTED" VARCHAR2(50 BYTE), 
	"MV_DATE_ENDED" VARCHAR2(50 BYTE), 
	"MV_RUNNING_TIME" NUMBER, 
	"MV_GENRE" VARCHAR2(50 BYTE), 
	"MV_INFO" VARCHAR2(3000 BYTE), 
	"MV_TICKET_SALES" NUMBER DEFAULT 0, 
	"MV_RATING_TOTAL" NUMBER DEFAULT 0, 
	"MV_RATING_CNT" NUMBER DEFAULT 0, 
	"MV_RATING_AVG" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_MEMBER" 
   (	"MMB_ID" VARCHAR2(100 BYTE), 
	"MMB_PASSWORD" VARCHAR2(100 BYTE), 
	"MMB_EMAIL" VARCHAR2(100 BYTE), 
	"MMB_PHONE" VARCHAR2(100 BYTE), 
	"MMB_BIRTHDAY" VARCHAR2(50 BYTE), 
	"MMB_ADMIN_CHECK" NUMBER DEFAULT 0, 
	"BRC_ID" NUMBER DEFAULT NULL, 
	"MMB_RESIGN_CHECK" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_BRANCH
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PJ_BRANCH" 
   (	"BRC_ID" NUMBER, 
	"BRC_AREA" NUMBER, 
	"BRC_NAME" VARCHAR2(100 BYTE), 
	"BRC_THEATER_NUMBERS" NUMBER, 
	"BRC_THEATER_SEATS" VARCHAR2(500 BYTE), 
	"BRC_INFO" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_TICKET_PK" ON "SCOTT"."PJ_TICKET" ("TK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_SCHEDULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_SCHEDULE_PK" ON "SCOTT"."PJ_SCHEDULE" ("SCD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_REVIEW_PK" ON "SCOTT"."PJ_REVIEW" ("RV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_MOVIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_MOVIE_PK" ON "SCOTT"."PJ_MOVIE" ("MV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_MEMBER_PK" ON "SCOTT"."PJ_MEMBER" ("MMB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PJ_BRANCH_PK" ON "SCOTT"."PJ_BRANCH" ("BRC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PJ_SCHEDULE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_SCHEDULE_ID_TRIGGER" 
before insert on PJ_SCHEDULE
for each row
begin
    select seq_PJ_SCHEDULE.nextval into :new.SCD_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_SCHEDULE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_REVIEW_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_REVIEW_ID_TRIGGER" 
before insert on PJ_REVIEW
for each row
begin
    select seq_PJ_REVIEW.nextval into :new.RV_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_REVIEW_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_REVIEW_DATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_REVIEW_DATE_TRIGGER" 
before update of RV_CONTENT, RV_RATING on PJ_REVIEW
for each row
begin
    select sysdate into :new.RV_DATE_CREATED from dual;
end;
/
ALTER TRIGGER "SCOTT"."PJ_REVIEW_DATE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_MOVIE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_MOVIE_ID_TRIGGER" 
before insert on PJ_MOVIE
for each row
begin
    select seq_PJ_MOVIE.nextval into :new.MV_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_MOVIE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_BRANCH_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_BRANCH_ID_TRIGGER" 
before insert on PJ_BRANCH
for each row
begin
    select seq_PJ_BRANCH.nextval into :new.BRC_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_BRANCH_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_TICKET_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_TICKET_ID_TRIGGER" 
before insert on PJ_TICKET
for each row
begin
    select seq_PJ_TICKET.nextval into :new.TK_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_TICKET_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_TICKET_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_TICKET_ID_TRIGGER" 
before insert on PJ_TICKET
for each row
begin
    select seq_PJ_TICKET.nextval into :new.TK_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_TICKET_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_SCHEDULE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_SCHEDULE_ID_TRIGGER" 
before insert on PJ_SCHEDULE
for each row
begin
    select seq_PJ_SCHEDULE.nextval into :new.SCD_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_SCHEDULE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_REVIEW_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_REVIEW_ID_TRIGGER" 
before insert on PJ_REVIEW
for each row
begin
    select seq_PJ_REVIEW.nextval into :new.RV_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_REVIEW_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_REVIEW_DATE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_REVIEW_DATE_TRIGGER" 
before update of RV_CONTENT, RV_RATING on PJ_REVIEW
for each row
begin
    select sysdate into :new.RV_DATE_CREATED from dual;
end;
/
ALTER TRIGGER "SCOTT"."PJ_REVIEW_DATE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_MOVIE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_MOVIE_ID_TRIGGER" 
before insert on PJ_MOVIE
for each row
begin
    select seq_PJ_MOVIE.nextval into :new.MV_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_MOVIE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_BRANCH_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."PJ_BRANCH_ID_TRIGGER" 
before insert on PJ_BRANCH
for each row
begin
    select seq_PJ_BRANCH.nextval into :new.BRC_ID from dual;
    end;
/
ALTER TRIGGER "SCOTT"."PJ_BRANCH_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_TICKET
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_TICKET" ADD CONSTRAINT "PJ_TICKET_PK" PRIMARY KEY ("TK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("TK_PRICE_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("TK_SEAT_LIST" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("TK_PEOPLE_LIST" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("MV_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("SCD_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("MMB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_TICKET" MODIFY ("TK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PJ_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_SCHEDULE" ADD CONSTRAINT "PJ_SCHEDULE_PK" PRIMARY KEY ("SCD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_SEAT_BOOKED_CNT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_SEAT_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_THEATER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("MV_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("BRC_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" MODIFY ("SCD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PJ_REVIEW
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_REVIEW" ADD CONSTRAINT "PJ_REVIEW_PK" PRIMARY KEY ("RV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("RV_DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("RV_RATING" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("RV_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("MMB_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("MV_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_REVIEW" MODIFY ("RV_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PJ_MOVIE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_MOVIE" ADD CONSTRAINT "PJ_MOVIE_PK" PRIMARY KEY ("MV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_RATING_AVG" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_RATING_CNT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_RATING_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_TICKET_SALES" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_INFO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_GENRE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_RUNNING_TIME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_DATE_ENDED" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_DATE_STARTED" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MOVIE" MODIFY ("MV_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PJ_MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_RESIGN_CHECK" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" ADD CONSTRAINT "PJ_MEMBER_PK" PRIMARY KEY ("MMB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("BRC_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_ADMIN_CHECK" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_PHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_MEMBER" MODIFY ("MMB_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PJ_BRANCH
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_INFO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_BRANCH" ADD CONSTRAINT "PJ_BRANCH_PK" PRIMARY KEY ("BRC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_THEATER_SEATS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_THEATER_NUMBERS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_AREA" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PJ_BRANCH" MODIFY ("BRC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PJ_TICKET
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_TICKET" ADD CONSTRAINT "FK_MMB_ID_TK" FOREIGN KEY ("MMB_ID")
	  REFERENCES "SCOTT"."PJ_MEMBER" ("MMB_ID") ENABLE;
  ALTER TABLE "SCOTT"."PJ_TICKET" ADD CONSTRAINT "FK_MV_ID_TK" FOREIGN KEY ("MV_ID")
	  REFERENCES "SCOTT"."PJ_MOVIE" ("MV_ID") ENABLE;
  ALTER TABLE "SCOTT"."PJ_TICKET" ADD CONSTRAINT "FK_SCD_ID_TK" FOREIGN KEY ("SCD_ID")
	  REFERENCES "SCOTT"."PJ_SCHEDULE" ("SCD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_SCHEDULE" ADD CONSTRAINT "FK_BRC_ID_SCD" FOREIGN KEY ("BRC_ID")
	  REFERENCES "SCOTT"."PJ_BRANCH" ("BRC_ID") ENABLE;
  ALTER TABLE "SCOTT"."PJ_SCHEDULE" ADD CONSTRAINT "FK_MV_ID_SCD" FOREIGN KEY ("MV_ID")
	  REFERENCES "SCOTT"."PJ_MOVIE" ("MV_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_REVIEW
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_REVIEW" ADD CONSTRAINT "FK_MMB_ID_RV" FOREIGN KEY ("MMB_ID")
	  REFERENCES "SCOTT"."PJ_MEMBER" ("MMB_ID") ENABLE;
  ALTER TABLE "SCOTT"."PJ_REVIEW" ADD CONSTRAINT "FK_MV_ID_RV" FOREIGN KEY ("MV_ID")
	  REFERENCES "SCOTT"."PJ_MOVIE" ("MV_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PJ_MEMBER" ADD CONSTRAINT "FK_BRC_ID_MMB" FOREIGN KEY ("BRC_ID")
	  REFERENCES "SCOTT"."PJ_BRANCH" ("BRC_ID") ENABLE;
